### ISSUE TITLE
Web app missing

### ISSUE THREAD

**Issue by ggee** [OpenNetworkingFoundation/SampleTap#4]
Will the web app part of the sample be included?  The ONFTappingApp.config has a reference to a www-rootdir.

www-rootdir=/home/wiretap/ONF-ODL/OpenDaylight/controller/opendaylight/distribution/opendaylight/target/distribution.opendaylight-osgipackage/opendaylight/www/app

**Comment by andrewkpearce** [comment]
The web-ui source files were missing. I have added them to the repo under web-ui. Copy these files to a convenient location on the file system and then edit the ONFTappingApp.config to point to the web-ui/tapping-ui_2.6 directory, then launch OSGi.
